# Generated by Django 4.2.11 on 2024-05-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="crew",
            field=models.ManyToManyField(
                related_name="flights", to="airport.crew"
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("seat", "flight"), name="unique_seat"
            ),
        ),
    ]
